apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  destination:
    namespace: keda
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: {{ .Values.chart.chartName }}
    repoURL: {{ .Values.chart.repoURL }}
    targetRevision: {{ .Values.chart.version }}
    helm:
      releaseName: keda
      values: |-
        image:
          repository: {{ .Values.image.keda.repository }}
          tag: {{ .Values.image.keda.tag }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

