apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.operator.name }}
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.operator.name }}
spec:
  destination:
    namespace: keda
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: {{ .Values.keda.chart.chartName }}
    repoURL: {{ .Values.keda.chart.repoURL }}
    targetRevision: {{ .Values.keda.chart.version }}
    helm:
      releaseName: keda
      values: |-
        image:
          repository: {{ .Values.keda.image.repository }}:{{ .Values.keda.image.tag}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

