apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keda.labels" . | indent 4 }}
spec:
  destination:
    namespace: keda
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: {{ .Values.keda.chart.chartName }}
    repoURL: {{ .Values.keda.chart.repoURL }}
    targetRevision: {{ .Values.keda.chart.version }}
    helm:
      releaseName: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

